import numpy as np
import torch
import torch.nn.functional as F
from torch import nn

from .base_model import BaseModel


class ResBlock(nn.Module):
    def __init__(self, num_channels: int):
        super().__init__()
        self.conv1 = nn.Conv2d(num_channels, num_channels, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(num_channels)
        self.conv2 = nn.Conv2d(num_channels, num_channels, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(num_channels)

    def forward(self, x):
        residual = x
        x = F.relu(self.bn1(self.conv1(x)))
        x = self.bn2(self.conv2(x))
        x += residual
        x = F.relu(x)
        return x


class ResNet(BaseModel):
    def __init__(
        self,
        board_size: tuple[int, int],
        action_size: int,
        num_res_blocks: int,
        num_channels: int,
        device: torch.device,
    ):
        super(ResNet, self).__init__()  # type: ignore[no-untyped-call]

        self.device = device
        self.rows, self.cols = board_size
        self.action_size = action_size

        # Initial convolution
        self.input_conv = nn.Sequential(
            nn.Conv2d(3, num_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(num_channels),
            nn.ReLU(),
        )

        # Residual blocks
        self.residual_blocks = nn.ModuleList(
            [ResBlock(num_channels) for _ in range(num_res_blocks)]
        )

        # Policy head
        self.policy_head = nn.Sequential(
            nn.Conv2d(num_channels, 32, kernel_size=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.Flatten(),
            nn.Linear(32 * self.rows * self.cols, self.action_size),
        )

        # Value head from https://github.com/foersterrobert/AlphaZeroFromScratch
        self.value_head = nn.Sequential(
            nn.Conv2d(num_channels, 3, kernel_size=3, padding=1),
            nn.BatchNorm2d(3),
            nn.ReLU(),
            nn.Flatten(),
            nn.Linear(3 * self.rows * self.cols, 1),
            # nn.Tanh(),
        )

        # Value head generated by Cursor
        # self.value_head = nn.Sequential(
        #     nn.Conv2d(num_channels, 32, kernel_size=1),
        #     nn.BatchNorm2d(32),
        #     nn.ReLU(),
        #     nn.Flatten(),
        #     nn.Linear(32 * self.rows * self.cols, 256),
        #     nn.ReLU(),
        #     nn.Dropout(0.3),
        #     nn.Linear(256, 1),
        # )

        self.to(device)

    def forward(self, x):
        x = x.view(-1, 1, self.rows, self.cols)

        x = self.input_conv(x)

        for block in self.residual_blocks:
            x = block(x)

        action_logits = self.policy_head(x)
        value_logit = self.value_head(x)

        return action_logits, value_logit

    def predict(self, boards: list[np.ndarray]) -> tuple[list[np.ndarray], list[float]]:
        """
        Input: list of boards as numpy arrays of shape (rows, cols)
        Returns: probability distributions over actions and value estimates
        """
        # Convert list of boards to tensor
        boards_tensor = torch.FloatTensor(np.array(boards)).to(self.device)
        if boards_tensor.dim() == 2:  # Single board
            boards_tensor = boards_tensor.view(1, self.rows, self.cols)
        elif boards_tensor.dim() == 3:  # Batch of boards
            boards_tensor = boards_tensor.view(-1, self.rows, self.cols)

        self.eval()
        with torch.no_grad():
            action_logits, value_logit = self.forward(boards_tensor)
            action_probs = F.softmax(action_logits, dim=1)
            value = torch.tanh(value_logit)

        # Convert to list of numpy arrays
        action_probs_list = list(action_probs.cpu().numpy())
        value_list = list(value.cpu().numpy().flatten())

        return action_probs_list, value_list
